### ISSUE TITLE
Diagonal movements?

### ISSUE THREAD

**Issue by siddharthramesh** [dwalker-uk/TelloEduSwarmSearch#1]
Have you ever attempted to fly the Tello in Diagonal trajectories? ex: Left and forward combined (Pitch+roll) simultaneously. Cause as of now the commands can be sent only sequentially. Is there a way to achieve diagonal flying?

**Comment by dwalker-uk** [comment]
Hi, if you look at demo_all_functions.py you’ll see a command ‘fly.straight’ - that will go diagonally (in 3 dimensions).  It corresponds to the ‘go’ command in the Tello SDK - see the Ryze website for the SDK documentation.

But more broadly, Tello can’t perform more than one command at a time - that’s a fundamental limitation of the drone. So there is no way, for example, to turn / rotate whilst moving.
